export type TileMaterial = {
  id: string;
  manufacturer: string;
  collection: string;
  name: string;
  format: string;
  finish: string;
  color: string;
  colorGroup: string;
  textureUrl: string;
  downloadUrl: string;
  sourceUrl: string;
  sourceLabel: string;
  tags: string[];
};

export type TileGeometry = "rectangular-slab" | "strip";

export type TileDimensions = {
  widthCm: number;
  lengthCm: number;
  thicknessMm: number;
  geometry: TileGeometry;
};

export const tileMaterials: TileMaterial[] = [
  {
    id: "emil-tele-thassos",
    manufacturer: "Emilceramica",
    collection: "Tele di Marmo Revolution",
    name: "Thassos",
    format: "90 × 90 см",
    finish: "Natural",
    color: "Светлый",
    colorGroup: "Светлые",
    textureUrl: "./assets/materials/emil-thassos.webp",
    downloadUrl: "https://www.emilgroup.com/downloadarea/",
    sourceUrl: "https://www.emilgroup.com/collections/brand/emilceramica/tele-di-marmo-revolution/",
    sourceLabel: "Официальный каталог Emilceramica",
    tags: ["мрамор", "светлый", "90×90"],
  },
  {
    id: "emil-tele-calacatta-black",
    manufacturer: "Emilceramica",
    collection: "Tele di Marmo Revolution",
    name: "Calacatta Black",
    format: "120 × 278 см",
    finish: "Semi-polished",
    color: "Графит",
    colorGroup: "Чёрные",
    textureUrl: "./assets/materials/emil-calacatta-black.webp",
    downloadUrl: "https://www.emilgroup.com/downloadarea/",
    sourceUrl: "https://www.emilgroup.com/collections/brand/emilceramica/tele-di-marmo-revolution/",
    sourceLabel: "Официальный каталог Emilceramica",
    tags: ["мрамор", "графит", "крупный формат"],
  },
  {
    id: "emil-tele-verde-saint-denis",
    manufacturer: "Emilceramica",
    collection: "Tele di Marmo Revolution",
    name: "Verde Saint Denis",
    format: "60 × 120 см",
    finish: "Natural",
    color: "Зелёный",
    colorGroup: "Зелёные",
    textureUrl: "./assets/materials/emil-verde-saint-denis.webp",
    downloadUrl: "https://www.emilgroup.com/downloadarea/",
    sourceUrl: "https://www.emilgroup.com/collections/brand/emilceramica/tele-di-marmo-revolution/",
    sourceLabel: "Официальный каталог Emilceramica",
    tags: ["мрамор", "зелёный", "60×120"],
  },
  {
    id: "41zero42-solo-grey",
    manufacturer: "41zero42",
    collection: "Solo",
    name: "Solo Grey",
    format: "60 × 120 см",
    finish: "Natural rectified",
    color: "Серый",
    colorGroup: "Серые",
    textureUrl: "./assets/materials/41zero42-solo-grey.webp",
    downloadUrl: "https://www.41zero42.com/wp-content/uploads/solo/solo_minimali.zip",
    sourceUrl: "https://www.41zero42.com/collections/solo-eng/",
    sourceLabel: "Страница коллекции 41zero42",
    tags: ["камень", "серый", "официальная коллекция"],
  },
  {
    id: "florim-stone-calacatta",
    manufacturer: "Florim",
    collection: "Stones & More 2.0",
    name: "Stone Calacatta",
    format: "120 × 280 см",
    finish: "Glossy / Matte Soft",
    color: "Светлый",
    colorGroup: "Светлые",
    textureUrl: "./assets/materials/florim-stone-calacatta.webp",
    downloadUrl: "https://www.florim.com/en/products/all-collections/stones-more-20/stone-calacatta",
    sourceUrl: "https://www.florim.com/en/products/all-collections/stones-more-20/stone-calacatta",
    sourceLabel: "Официальная страница Florim",
    tags: ["мрамор", "светлый", "глянец"],
  },
  {
    id: "florim-stone-marfil",
    manufacturer: "Florim",
    collection: "Stones & More 2.0",
    name: "Stone Marfil",
    format: "120 × 280 см",
    finish: "Matte Soft",
    color: "Бежевый",
    colorGroup: "Светлые",
    textureUrl: "./assets/materials/florim-stone-marfil.webp",
    downloadUrl: "https://www.florim.com/en/products/all-collections/stones-more-20/stone-marfil",
    sourceUrl: "https://www.florim.com/en/products/all-collections/stones-more-20/stone-marfil",
    sourceLabel: "Официальная страница Florim",
    tags: ["камень", "бежевый", "matte"],
  },
  {
    id: "florim-sahara-noir",
    manufacturer: "Florim",
    collection: "Stones & More 2.0",
    name: "Sahara Noir",
    format: "160 × 320 см",
    finish: "Matte",
    color: "Чёрный",
    colorGroup: "Чёрные",
    textureUrl: "./assets/materials/florim-sahara-noir-texture.webp",
    downloadUrl: "https://www.florim.com/en/products/all-collections/stones-more-20",
    sourceUrl: "https://www.florim.com/en/products/all-collections/stones-more-20",
    sourceLabel: "Официальная страница Florim",
    tags: ["камень", "чёрный", "крупный формат"],
  },
  {
    id: "florim-stone-calacatta-smooth",
    manufacturer: "Florim",
    collection: "Stones & More 2.0",
    name: "Stone Calacatta Smooth",
    format: "120 × 280 см",
    finish: "Matte Soft",
    color: "Светлый",
    colorGroup: "Светлые",
    textureUrl: "./assets/materials/florim-stone-calacatta.webp",
    downloadUrl: "https://florim-cdn.thron.com/api/v1/content-delivery/shares/rf8vac/contents/d3477f01-d637-4eff-91b9-1e279b29de09/image/757761_01.jpg",
    sourceUrl: "https://www.florim.com/en/products/all-collections/stones-more-20/stone-calacatta",
    sourceLabel: "Официальная страница Florim",
    tags: ["мрамор", "светлый", "matte soft"],
  },
  {
    id: "florim-stone-marfil-smooth",
    manufacturer: "Florim",
    collection: "Stones & More 2.0",
    name: "Stone Marfil Smooth",
    format: "120 × 280 см",
    finish: "Matte Soft",
    color: "Бежевый",
    colorGroup: "Светлые",
    textureUrl: "./assets/materials/florim-stone-marfil.webp",
    downloadUrl: "https://florim-cdn.thron.com/api/v1/content-delivery/shares/rf8vac/contents/d297de22-1638-4029-a5fb-2cae52f8a8ae/image/757759_01.jpg",
    sourceUrl: "https://www.florim.com/en/products/all-collections/stones-more-20/stone-marfil",
    sourceLabel: "Официальная страница Florim",
    tags: ["камень", "бежевый", "matte soft"],
  },
  {
    id: "florim-amani-bronze-matte",
    manufacturer: "Florim",
    collection: "Stones & More 2.0",
    name: "Amani Bronze",
    format: "60 × 120 см",
    finish: "Matte",
    color: "Бронзовый",
    colorGroup: "Коричневые",
    textureUrl: "./assets/materials/florim-amani-bronze.webp",
    downloadUrl: "https://florim-cdn.thron.com/api/v1/content-delivery/shares/rf8vac/contents/91cd2395-efef-44be-a674-f67fdb974439/image/756230_01.jpg",
    sourceUrl: "https://www.florim.com/en/products/all-collections/stones-more-20/amani-bronze",
    sourceLabel: "Официальная страница Florim",
    tags: ["камень", "бронзовый", "matte"],
  },
  {
    id: "florim-amani-bronze-glossy",
    manufacturer: "Florim",
    collection: "Stones & More 2.0",
    name: "Amani Bronze Glossy",
    format: "60 × 120 см",
    finish: "Glossy",
    color: "Бронзовый",
    colorGroup: "Коричневые",
    textureUrl: "./assets/materials/florim-amani-bronze.webp",
    downloadUrl: "https://florim-cdn.thron.com/api/v1/content-delivery/shares/rf8vac/contents/b7f3d7b9-6333-469f-99f0-ffa862bb5b71/image/756233_01.jpg",
    sourceUrl: "https://www.florim.com/en/products/all-collections/stones-more-20/amani-bronze",
    sourceLabel: "Официальная страница Florim",
    tags: ["камень", "бронзовый", "глянец"],
  },
  {
    id: "florim-stone-calacatta-black-glossy",
    manufacturer: "Florim",
    collection: "Stones & More 2.0",
    name: "Stone Calacatta Black",
    format: "60 × 120 см",
    finish: "Glossy",
    color: "Графит",
    colorGroup: "Чёрные",
    textureUrl: "./assets/materials/florim-stone-calacatta-black.webp",
    downloadUrl: "https://florim-cdn.thron.com/api/v1/content-delivery/shares/rf8vac/contents/37d94674-c44b-4871-b3fc-b6369e9d9038/image/756232_01.jpg",
    sourceUrl: "https://www.florim.com/en/products/all-collections/stones-more-20/stone-calacatta-black",
    sourceLabel: "Официальная страница Florim",
    tags: ["мрамор", "графит", "глянец"],
  },
  {
    id: "florim-stone-calacatta-black-smooth",
    manufacturer: "Florim",
    collection: "Stones & More 2.0",
    name: "Stone Calacatta Black Smooth",
    format: "60 × 120 см",
    finish: "Smooth",
    color: "Графит",
    colorGroup: "Чёрные",
    textureUrl: "./assets/materials/florim-stone-calacatta-black.webp",
    downloadUrl: "https://florim-cdn.thron.com/api/v1/content-delivery/shares/rf8vac/contents/92737818-f460-4c62-9451-f648984cb584/image/756229_01.jpg",
    sourceUrl: "https://www.florim.com/en/products/all-collections/stones-more-20/stone-calacatta-black",
    sourceLabel: "Официальная страница Florim",
    tags: ["мрамор", "графит", "smooth"],
  },
  {
    id: "florim-sahara-noir-glossy",
    manufacturer: "Florim",
    collection: "Stones & More 2.0",
    name: "Stone Sahara Noir Glossy",
    format: "120 × 240 см",
    finish: "Glossy",
    color: "Чёрный",
    colorGroup: "Чёрные",
    textureUrl: "./assets/materials/florim-sahara-noir-texture.webp",
    downloadUrl: "https://florim-cdn.thron.com/api/v1/content-delivery/shares/rf8vac/contents/d81f94bb-b1fe-429a-bd91-825cd72d579a/image/752806_01.jpg",
    sourceUrl: "https://www.florim.com/en/products/all-collections/stones-more-20/stone-sahara-noir",
    sourceLabel: "Официальная страница Florim",
    tags: ["камень", "чёрный", "глянец"],
  },
  {
    id: "emil-tele-blu-ande",
    manufacturer: "Emilceramica",
    collection: "Tele di Marmo Revolution",
    name: "Blu Ande",
    format: "120 × 278 см",
    finish: "Natural",
    color: "Синий",
    colorGroup: "Синие",
    textureUrl: "./assets/materials/emil-blu-ande.webp",
    downloadUrl: "https://www.emilgroup.com/downloadarea/",
    sourceUrl: "https://www.emilgroup.com/collections/brand/emilceramica/tele-di-marmo-revolution/",
    sourceLabel: "Официальный каталог Emilceramica",
    tags: ["мрамор", "синий", "крупный формат"],
  },
  {
    id: "emil-tele-thassos-60x120",
    manufacturer: "Emilceramica",
    collection: "Tele di Marmo Revolution",
    name: "Thassos 60 × 120",
    format: "60 × 120 см",
    finish: "Natural",
    color: "Светлый",
    colorGroup: "Светлые",
    textureUrl: "./assets/materials/emil-thassos-60x120.webp",
    downloadUrl: "https://www.emilgroup.com/downloadarea/",
    sourceUrl: "https://www.emilgroup.com/collections/brand/emilceramica/tele-di-marmo-revolution/",
    sourceLabel: "Официальный каталог Emilceramica",
    tags: ["мрамор", "светлый", "60×120"],
  },
  {
    id: "emil-tele-calacatta-black-60x120",
    manufacturer: "Emilceramica",
    collection: "Tele di Marmo Revolution",
    name: "Calacatta Black 60 × 120",
    format: "60 × 120 см",
    finish: "Semi-polished",
    color: "Графит",
    colorGroup: "Чёрные",
    textureUrl: "./assets/materials/emil-calacatta-black-60x120.webp",
    downloadUrl: "https://www.emilgroup.com/downloadarea/",
    sourceUrl: "https://www.emilgroup.com/collections/brand/emilceramica/tele-di-marmo-revolution/",
    sourceLabel: "Официальный каталог Emilceramica",
    tags: ["мрамор", "графит", "60×120"],
  },
  {
    id: "41zero42-solo-out-grey",
    manufacturer: "41zero42",
    collection: "Solo",
    name: "Solo Out Grey",
    format: "40 × 80 см",
    finish: "Natural rectified",
    color: "Серый",
    colorGroup: "Серые",
    textureUrl: "./assets/materials/41zero42-solo-out-grey.webp",
    downloadUrl: "https://www.41zero42.com/wp-content/uploads/solo/solo_minimali.zip",
    sourceUrl: "https://www.41zero42.com/collections/solo-eng/",
    sourceLabel: "Страница коллекции 41zero42",
    tags: ["камень", "серый", "мозаика"],
  },
  {
    id: "41zero42-solo-white-5x80",
    manufacturer: "41zero42",
    collection: "Solo",
    name: "Solo White",
    format: "5 × 80 см",
    finish: "Natural rectified",
    color: "Белый",
    colorGroup: "Светлые",
    textureUrl: "./assets/materials/41zero42-solo-white-floor.webp",
    downloadUrl: "https://www.41zero42.com/wp-content/uploads/solo/solo_minimali.zip",
    sourceUrl: "https://www.41zero42.com/collections/solo-eng/",
    sourceLabel: "Страница коллекции 41zero42",
    tags: ["камень", "белый", "узкий формат"],
  },
  {
    id: "41zero42-solo-white-60x120",
    manufacturer: "41zero42",
    collection: "Solo",
    name: "Wall Solo White",
    format: "60 × 120 см",
    finish: "Natural rectified",
    color: "Белый",
    colorGroup: "Светлые",
    textureUrl: "./assets/materials/41zero42-solo-white-wall.webp",
    downloadUrl: "https://www.41zero42.com/wp-content/uploads/solo/solo_minimali.zip",
    sourceUrl: "https://www.41zero42.com/collections/solo-eng/",
    sourceLabel: "Страница коллекции 41zero42",
    tags: ["камень", "белый", "60×120"],
  },
];

// Physical dimensions used by the scene. Width/length come from the catalog
// format; thickness follows the manufacturer's format family where listed,
// with the standard ceramic thickness for records that expose only the face
// format. The visualizer keeps these values separate from display copy so the
// model and ruler cannot drift apart.
export const tileDimensionsById: Record<string, TileDimensions> = {
  "emil-tele-thassos": { widthCm: 90, lengthCm: 90, thicknessMm: 8.5, geometry: "rectangular-slab" },
  "emil-tele-calacatta-black": { widthCm: 120, lengthCm: 278, thicknessMm: 6.5, geometry: "rectangular-slab" },
  "emil-tele-verde-saint-denis": { widthCm: 60, lengthCm: 120, thicknessMm: 8.5, geometry: "rectangular-slab" },
  "41zero42-solo-grey": { widthCm: 60, lengthCm: 120, thicknessMm: 9, geometry: "rectangular-slab" },
  "florim-stone-calacatta": { widthCm: 120, lengthCm: 280, thicknessMm: 6.5, geometry: "rectangular-slab" },
  "florim-stone-marfil": { widthCm: 120, lengthCm: 280, thicknessMm: 6.5, geometry: "rectangular-slab" },
  "florim-sahara-noir": { widthCm: 160, lengthCm: 320, thicknessMm: 6.5, geometry: "rectangular-slab" },
  "florim-stone-calacatta-smooth": { widthCm: 120, lengthCm: 280, thicknessMm: 6.5, geometry: "rectangular-slab" },
  "florim-stone-marfil-smooth": { widthCm: 120, lengthCm: 280, thicknessMm: 6.5, geometry: "rectangular-slab" },
  "florim-amani-bronze-matte": { widthCm: 60, lengthCm: 120, thicknessMm: 8.5, geometry: "rectangular-slab" },
  "florim-amani-bronze-glossy": { widthCm: 60, lengthCm: 120, thicknessMm: 8.5, geometry: "rectangular-slab" },
  "florim-stone-calacatta-black-glossy": { widthCm: 60, lengthCm: 120, thicknessMm: 8.5, geometry: "rectangular-slab" },
  "florim-stone-calacatta-black-smooth": { widthCm: 60, lengthCm: 120, thicknessMm: 8.5, geometry: "rectangular-slab" },
  "florim-sahara-noir-glossy": { widthCm: 120, lengthCm: 240, thicknessMm: 6.5, geometry: "rectangular-slab" },
  "emil-tele-blu-ande": { widthCm: 120, lengthCm: 278, thicknessMm: 6.5, geometry: "rectangular-slab" },
  "emil-tele-thassos-60x120": { widthCm: 60, lengthCm: 120, thicknessMm: 8.5, geometry: "rectangular-slab" },
  "emil-tele-calacatta-black-60x120": { widthCm: 60, lengthCm: 120, thicknessMm: 8.5, geometry: "rectangular-slab" },
  "41zero42-solo-out-grey": { widthCm: 40, lengthCm: 80, thicknessMm: 9, geometry: "rectangular-slab" },
  "41zero42-solo-white-5x80": { widthCm: 5, lengthCm: 80, thicknessMm: 9, geometry: "strip" },
  "41zero42-solo-white-60x120": { widthCm: 60, lengthCm: 120, thicknessMm: 9, geometry: "rectangular-slab" },
};

export function getTileDimensions(material: Pick<TileMaterial, "id" | "format">): TileDimensions {
  const knownDimensions = tileDimensionsById[material.id];
  if (knownDimensions) return knownDimensions;

  const match = material.format.match(/([\d.]+)\s*[×x]\s*([\d.]+)/i);
  const widthCm = Number(match?.[1] ?? 60);
  const lengthCm = Number(match?.[2] ?? 120);
  return {
    widthCm,
    lengthCm,
    thicknessMm: 8.5,
    geometry: widthCm <= 10 ? "strip" : "rectangular-slab",
  };
}

// Several catalog records describe different finishes of the same source image.
// The visualizer should not present identical swatches as separate materials.
export const visualizerMaterials = tileMaterials.filter((material, index, materials) => (
  materials.findIndex((candidate) => candidate.textureUrl === material.textureUrl) === index
));

export const materialManufacturers = ["Все производители", ...Array.from(new Set(visualizerMaterials.map((material) => material.manufacturer)))];
export const materialColorGroups = ["Все цвета", ...Array.from(new Set(visualizerMaterials.map((material) => material.colorGroup)))];
