// Generated by dts-bundle-generator v9.5.1

export type EventPostCategory = "event" | "objects" | "materials" | "news" | "inspiration";
export type TelegramPost = {
	id: string;
	telegramMessageId: number;
	channelUsername: string;
	publishedAt: string;
	category: EventPostCategory;
	title: string;
	text: string;
	excerpt: string;
	imageUrl?: string | null;
	imageUrls: string[];
	telegramUrl: string;
};
export type FeaturedEvent = {
	id: string;
	title: string;
	startsAt: string;
	displayTimezone: string;
	location: string;
	description: string;
	capacity?: number | null;
	imageUrl?: string | null;
};
export type EventsPageData = {
	featuredEvent: FeaturedEvent | null;
	posts: TelegramPost[];
	channelUrl: string;
	lastSyncedAt: string | null;
};
export type EventReplyKeyboardMode = "idle" | "draft" | "confirm";
declare function eventReplyKeyboard(mode?: EventReplyKeyboardMode | boolean): {
	keyboard: {
		text: string;
	}[][];
	resize_keyboard: boolean;
	is_persistent: boolean;
};
export type TelegramEventMessage = {
	chat: {
		id: number;
		type?: string;
	};
	text?: string;
};
export type TelegramUpdate = {
	update_id: number;
	message?: TelegramEventMessage;
};
export type TelegramWebhookResponse = {
	method: "sendMessage";
	chat_id: number;
	text: string;
	reply_markup: ReturnType<typeof eventReplyKeyboard>;
};
export declare function health(): Promise<{
	status: string;
	timestamp: string;
	db: string;
	env: "development" | "production";
}>;
export declare function getEventsPage(): Promise<EventsPageData>;
export declare function syncTelegramFeed(): Promise<{
	synced: number;
	syncedAt: string;
}>;
export declare function createEventRegistration(input: {
	fullName: string;
	phone: string;
	eventId?: string;
	event?: FeaturedEvent;
}): Promise<{
	id: string;
	notification: {
		telegram: {
			status: "sent";
			value: string;
		} | {
			status: "failed";
			error: string;
		};
		email: {
			status: "sent";
			value: string;
		} | {
			status: "failed";
			error: string;
		};
	};
}>;
export declare function createContactRequest(input: {
	fullName: string;
	phone: string;
}): Promise<{
	id: string;
	notification: {
		telegram: {
			status: "sent";
			value: string;
		} | {
			status: "failed";
			error: string;
		};
		email: {
			status: "sent";
			value: string;
		} | {
			status: "failed";
			error: string;
		};
	};
}>;
export declare function handleTelegramWebhookUpdate(update: TelegramUpdate): Promise<TelegramWebhookResponse | null>;
export declare function syncTelegramBot(): Promise<{
	status: "not_configured";
	processed: number;
} | {
	status: "webhook_active";
	processed: number;
} | {
	status: "ok";
	processed: number;
}>;

export {};
