// Generated by dts-bundle-generator v9.5.1

export type EventPostCategory = "event" | "objects" | "materials" | "news" | "inspiration";
export type TelegramPost = {
	id: string;
	telegramMessageId: number;
	channelUsername: string;
	publishedAt: string;
	category: EventPostCategory;
	title: string;
	text: string;
	excerpt: string;
	imageUrl?: string | null;
	imageUrls: string[];
	telegramUrl: string;
};
export type FeaturedEvent = {
	id: string;
	title: string;
	startsAt: string;
	displayTimezone: string;
	location: string;
	description: string;
	capacity?: number | null;
	imageUrl?: string | null;
};
export type EventsPageData = {
	featuredEvent: FeaturedEvent | null;
	posts: TelegramPost[];
	channelUrl: string;
	lastSyncedAt: string | null;
};
export declare function health(): Promise<{
	status: string;
	timestamp: string;
	db: string;
	env: "development" | "production";
}>;
export declare function getEventsPage(): Promise<EventsPageData>;
export declare function syncTelegramFeed(): Promise<{
	synced: number;
	syncedAt: string;
}>;
export declare function createEventRegistration(input: {
	fullName: string;
	phone: string;
	eventId?: string;
	event?: FeaturedEvent;
}): Promise<{
	id: string;
	notification: "not_configured" | "sent";
}>;
export declare function createContactRequest(input: {
	fullName: string;
	phone: string;
}): Promise<{
	id: string;
	notification: "not_configured" | "sent";
}>;
export declare function syncTelegramBot(): Promise<{
	status: "not_configured";
	processed: number;
} | {
	status: "ok";
	processed: number;
}>;

export {};
